### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DanielLarsenNZ** [superpikar/learn-classic-asp#1]
Cool project! OK to share? Would you mind adding a license file please.

**Comment by superpikar** [comment]
Sure, is okay to share. I will add the license file in a few minutes

**Comment by superpikar** [comment]
added MIT license in the repo @DanielLarsenNZ 
see : https://github.com/superpikar/learn-classic-asp/commit/44ee900de021d63918d6763c56a5a7ff06cbd7ac

**Comment by DanielLarsenNZ** [comment]
Thank you so much @superpikar - this is a really useful project 👏
